API_KEY = "QOfopOmO9jh8F8X0oPSO9FgDXjNisqnu2p0EmwD2xGqSG2zy1bcH5dinvhZDV4tf"
SECRET_KEY = "9gwadE3RudvdzqoxBrSLBshDb9h5jEG7rCkHql3MdBXWpjWxd7wh0rOnDQWPBYvN"


SYMBOL = "ETHUSDT"
POSITION_SIZE = 0.01

# GridBot Settings
NUM_BUY_GRID_LINES = 5
NUM_SELL_GRID_LINES = 5
GRID_SIZE = 0.5

CHECK_ORDERS_FREQUENCY = 2
CLOSED_ORDER_STATUS = "FILLED"
