API_KEY = ""
SECRET_KEY = ""


SYMBOL = "ETHUSDT"
POSITION_SIZE = 0.01

# GridBot Settings
NUM_BUY_GRID_LINES = 5
NUM_SELL_GRID_LINES = 5
GRID_SIZE = 0.5

CHECK_ORDERS_FREQUENCY = 2
CLOSED_ORDER_STATUS = "FILLED"
